### ISSUE TITLE
panic: assertion failed: write: circular dependency occurred

### ISSUE THREAD

**Issue by thindata** [odeke-em/drive#1086]
For about 2 weeks now i've been getting the following errors, I haven't upgraded/changed any software so unsure as to the reason?

when attempting to do a push I get

`Addition count 9 src: 4.05MB dest: 491.70KB
0 / 4243592 [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0.00 % panic: assertion failed: write: circular dependency occurred

goroutine 30 [running]:
github.com/boltdb/bolt._assert(0x10c31300, 0x463de8, 0x23, 0x0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/boltdb/bolt/db.go:782 +0xc4
github.com/boltdb/bolt.(*node).write(0x10c2e180, 0x10c31000)
        /cshome/odeke/go/src/github.com/boltdb/bolt/node.go:221 +0x604
github.com/boltdb/bolt.(*node).spill(0x10c2e180, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/boltdb/bolt/node.go:373 +0x4f0
github.com/boltdb/bolt.(*Bucket).spill(0x10c1cd40, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/boltdb/bolt/bucket.go:541 +0x14c
github.com/boltdb/bolt.(*Bucket).spill(0x10c0e58c, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/boltdb/bolt/bucket.go:508 +0x90c
github.com/boltdb/bolt.(*Tx).Commit(0x10c0e580, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/boltdb/bolt/tx.go:162 +0x1c4
github.com/boltdb/bolt.(*DB).Update(0x10c06200, 0x108abe24, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/boltdb/bolt/db.go:554 +0x110
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0x1088ec80, 0x10c2e0c0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/config/config.go:281 +0x13c
github.com/odeke-em/drive/src.(*Commands).remoteMod(0x1088f320, 0x10ab4c80, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:474 +0x9d0
github.com/odeke-em/drive/src.(*Commands).remoteAdd(0x1088f320, 0x10ab4c80, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:484 +0x34
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.remoteAdd)-fm(0x10ab4c80, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:267 +0x34
github.com/odeke-em/drive/src.(*Commands).playPushChanges.func3.1(0x10819700, 0x1088f320, 0x10ab4c80, 0x10a43c68, 0x10ae1080, 0x10a8be50, 0x10ae1040)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:349 +0x1a8
created by github.com/odeke-em/drive/src.(*Commands).playPushChanges.func3
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:361 +0xa0

goroutine 1 [chan receive]:
github.com/odeke-em/drive/src.(*Commands).playPushChanges(0x1088f320, 0x10ae0800, 0x9, 0x10, 0x10a43b68, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:366 +0x454
github.com/odeke-em/drive/src.(*Commands).Push(0x1088f320, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:155 +0x1328
main.(*pushCmd).Run(0x10814320, 0x1080a0b8, 0x1, 0x1, 0x1088eb40)
        /cshome/odeke/go/src/github.com/odeke-em/drive/cmd/drive/main.go:796 +0x1b0
github.com/odeke-em/command.Run()
        /cshome/odeke/go/src/github.com/odeke-em/command/command.go:202 +0xac
github.com/odeke-em/command.ParseAndRun()
        /cshome/odeke/go/src/github.com/odeke-em/command/command.go:209 +0x18
main.main()
        /cshome/odeke/go/src/github.com/odeke-em/drive/cmd/drive/main.go:120 +0x2158

goroutine 5 [syscall]:
os/signal.loop()
        /cshome/odeke/goroot/src/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /cshome/odeke/goroot/src/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 6 [select, locked to thread]:
runtime.gopark(0x4b8d98, 0x1081e78c, 0x410ed0, 0x6, 0x50818, 0x2)
        /cshome/odeke/goroot/src/go/src/runtime/proc.go:185 +0x148
runtime.selectgoImpl(0x1081e78c, 0x0, 0xc)
        /cshome/odeke/goroot/src/go/src/runtime/select.go:392 +0x14d4
runtime.selectgo(0x1081e78c)
        /cshome/odeke/goroot/src/go/src/runtime/select.go:212 +0x10
runtime.ensureSigM.func1()
        /cshome/odeke/goroot/src/go/src/runtime/signal1_unix.go:227 +0x428
runtime.goexit()
        /cshome/odeke/goroot/src/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 7 [chan receive]:
github.com/odeke-em/drive/src.(*Commands).Push.func1(0x10893180, 0x108955b0, 0x1088f320)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:51 +0x38
created by github.com/odeke-em/drive/src.(*Commands).Push
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:55 +0x284

goroutine 27 [chan receive]:
github.com/odeke-em/drive/src.(*Commands).playPushChanges.func1(0x1088f320)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:291 +0x3c
created by github.com/odeke-em/drive/src.(*Commands).playPushChanges
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:294 +0x1c8

goroutine 14 [IO wait]:
net.runtime_pollWait(0xb6e78af8, 0x72, 0x1080e0d0)
        /cshome/odeke/goroot/src/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10893978, 0x72, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10893978, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10893940, 0x10870c00, 0x400, 0x400, 0x0, 0xb6e73030, 0x1080e0d0)
        /cshome/odeke/goroot/src/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10820f50, 0x10870c00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x108c0100, 0xb6e78db0, 0x10820f50, 0x5, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:455 +0xc8
crypto/tls.(*Conn).readRecord(0x10876340, 0x4b8d17, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:540 +0x240
crypto/tls.(*Conn).Read(0x10876340, 0x108c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:901 +0x13c
net/http.noteEOFReader.Read(0xb6e79150, 0x10876340, 0x108981ac, 0x108c3000, 0x1000, 0x1000, 0x22dc7c, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x10a4ce40, 0x108c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10a416e0)
        /cshome/odeke/goroot/src/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10a416e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x10898180)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:685 +0xab4

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0x10898180)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:686 +0xad0

goroutine 21 [IO wait]:
net.runtime_pollWait(0xb6e78a80, 0x72, 0x1080e0d0)
        /cshome/odeke/goroot/src/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10a27778, 0x72, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10a27778, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10a27740, 0x10a70000, 0x1000, 0x1000, 0x0, 0xb6e73030, 0x1080e0d0)
        /cshome/odeke/goroot/src/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10a42e08, 0x10a70000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x10a5e980, 0xb6e78db0, 0x10a42e08, 0x5, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:455 +0xc8
crypto/tls.(*Conn).readRecord(0x10876680, 0x4b8d17, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:540 +0x240
crypto/tls.(*Conn).Read(0x10876680, 0x10a71000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:901 +0x13c
net/http.noteEOFReader.Read(0xb6e79150, 0x10876680, 0x109ef0ac, 0x10a71000, 0x1000, 0x1000, 0x22dc7c, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x10a83db0, 0x10a71000, 0x1000, 0x1000, 0x10b558e0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10a85ec0)
        /cshome/odeke/goroot/src/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10a85ec0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x109ef080)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:685 +0xab4

goroutine 22 [select]:
net/http.(*persistConn).writeLoop(0x109ef080)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:686 +0xad0

goroutine 26 [select]:
github.com/cheggaaa/pb.(*ProgressBar).writer(0x10ac2bb0)
        /cshome/odeke/go/src/github.com/cheggaaa/pb/pb.go:353 +0xe8
created by github.com/cheggaaa/pb.(*ProgressBar).Start
        /cshome/odeke/go/src/github.com/cheggaaa/pb/pb.go:105 +0xd4

goroutine 28 [chan receive]:
github.com/odeke-em/drive/src.(*Commands).playPushChanges.func2(0x10ae1000, 0x10ae0800, 0x9, 0x10, 0x10a8be50, 0x1088f320, 0x10ae1040)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:336 +0x36c
created by github.com/odeke-em/drive/src.(*Commands).playPushChanges
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:338 +0x3e0

goroutine 29 [chan receive]:
github.com/odeke-em/drive/src.(*Commands).playPushChanges.func3(0x10ae1000, 0x10ae0800, 0x1088f320, 0x10ae1080, 0x10a8be50, 0x10ae1040)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:341 +0x3c
created by github.com/odeke-em/drive/src.(*Commands).playPushChanges
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:363 +0x424

goroutine 31 [select]:
net/http.(*persistConn).roundTrip(0x10b27440, 0x10b55890, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1164 +0x978
net/http.(*Transport).RoundTrip(0x10846af0, 0x10b63dc0, 0x10b63dc0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:235 +0x428
golang.org/x/oauth2.(*Transport).RoundTrip(0x1088f2c0, 0x10b63d50, 0x12a, 0x0, 0x0)
        /cshome/odeke/go/src/golang.org/x/oauth2/transport.go:48 +0x1c0
net/http.send(0x10b63d50, 0xb6e77b10, 0x1088f2c0, 0x10b93500, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/client.go:220 +0x454
net/http.(*Client).send(0x1088f2e0, 0x10b63d50, 0xd4, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/client.go:143 +0x124
net/http.(*Client).doFollowingRedirects(0x1088f2e0, 0x10b63d50, 0x4b8bac, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/client.go:380 +0xa00
net/http.(*Client).Do(0x1088f2e0, 0x10b63d50, 0x430918, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/client.go:175 +0x98
google.golang.org/api/drive/v2.(*FilesListCall).doRequest(0x10ba7a5c, 0x4101b8, 0x4, 0x8, 0x0, 0x0)
        /cshome/odeke/go/src/google.golang.org/api/drive/v2/drive-gen.go:5985 +0x1218
google.golang.org/api/drive/v2.(*FilesListCall).Do(0x10ba7a5c, 0x0, 0x0, 0x0)
        /cshome/odeke/go/src/google.golang.org/api/drive/v2/drive-gen.go:5996 +0x40
github.com/odeke-em/drive/src.(*Remote).findByPathRecvRaw(0x108954c0, 0x10bbd2c0, 0x48, 0x10b137b8, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:890 +0x320
github.com/odeke-em/drive/src.(*Remote).findByPathRecvRaw(0x108954c0, 0x10bcae80, 0x1c, 0x10b137b0, 0x4, 0x4, 0x0, 0x10b137a0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:907 +0x5f8
github.com/odeke-em/drive/src.(*Remote).findByPathRecvRaw(0x108954c0, 0x410d80, 0x4, 0x10b137a8, 0x5, 0x5, 0x0, 0x10b137a0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:907 +0x5f8
github.com/odeke-em/drive/src.(*Remote).findByPathRecv(0x108954c0, 0x410d80, 0x4, 0x10b137a8, 0x5, 0x5, 0x10b137a0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:911 +0x64
github.com/odeke-em/drive/src.(*Remote).(github.com/odeke-em/drive/src.findByPathRecv)-fm(0x410d80, 0x4, 0x10b137a8, 0x5, 0x5, 0x6, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:239 +0x5c
github.com/odeke-em/drive/src.(*Remote).findByPath(0x108954c0, 0x10ae1400, 0x3a, 0x360800, 0x108185cc, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:243 +0x204
github.com/odeke-em/drive/src.(*Remote).FindByPath(0x108954c0, 0x10ae1400, 0x3a, 0x0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:247 +0x4c
github.com/odeke-em/drive/src.(*Commands).remoteMkdirAll(0x1088f320, 0x10ae1400, 0x3a, 0x0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:558 +0x164
github.com/odeke-em/drive/src.(*Commands).remoteMod(0x1088f320, 0x10ab54a0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:435 +0x2f8
github.com/odeke-em/drive/src.(*Commands).remoteAdd(0x1088f320, 0x10ab54a0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:484 +0x34
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.remoteAdd)-fm(0x10ab54a0, 0x0, 0x0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:267 +0x34
github.com/odeke-em/drive/src.(*Commands).playPushChanges.func3.1(0x10819700, 0x1088f320, 0x10ab54a0, 0x10a43c78, 0x10ae1080, 0x10a8be50, 0x10ae1040)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:349 +0x1a8
created by github.com/odeke-em/drive/src.(*Commands).playPushChanges.func3
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/push.go:361 +0xa0

goroutine 32 [chan receive]:
github.com/odeke-em/drive/src.(*Remote).UpsertByComparison.func1(0x10b7ce30, 0x108954c0)
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:761 +0x40
created by github.com/odeke-em/drive/src.(*Remote).UpsertByComparison
        /cshome/odeke/go/src/github.com/odeke-em/drive/src/remote.go:764 +0x1d8

goroutine 49 [IO wait]:
net.runtime_pollWait(0xb6e78990, 0x72, 0x1080e0d0)
        /cshome/odeke/goroot/src/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10bde4b8, 0x72, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10bde4b8, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10bde480, 0x10bee000, 0x400, 0x400, 0x0, 0xb6e73030, 0x1080e0d0)
        /cshome/odeke/goroot/src/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10b55138, 0x10bee000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x10bcbb00, 0xb6e78db0, 0x10b55138, 0x5, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:455 +0xc8
crypto/tls.(*Conn).readRecord(0x10b25860, 0x4b8d17, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:540 +0x240
crypto/tls.(*Conn).Read(0x10b25860, 0x10c1b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:901 +0x13c
net/http.noteEOFReader.Read(0xb6e79150, 0x10b25860, 0x10bce6ec, 0x10c1b000, 0x1000, 0x1000, 0x10bdfe80, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x10c0bfd0, 0x10c1b000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10c10a50)
        /cshome/odeke/goroot/src/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10c10a50, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x10bce6c0)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:685 +0xab4

goroutine 45 [runnable]:
net.runtime_pollWait(0xb6e78a08, 0x72, 0x1080e0d0)
        /cshome/odeke/goroot/src/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x10bb06b8, 0x72, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x10bb06b8, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x10bb0680, 0x10a6f400, 0x400, 0x400, 0x0, 0xb6e73030, 0x1080e0d0)
        /cshome/odeke/goroot/src/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x10b548e0, 0x10a6f400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x10bae8e0, 0xb6e78db0, 0x10b548e0, 0x5, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:455 +0xc8
crypto/tls.(*Conn).readRecord(0x10b25520, 0x4b8d17, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:540 +0x240
crypto/tls.(*Conn).Read(0x10b25520, 0x10bea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/crypto/tls/conn.go:901 +0x13c
net/http.noteEOFReader.Read(0xb6e79150, 0x10b25520, 0x10b2746c, 0x10bea000, 0x1000, 0x1000, 0x22dc7c, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x10bcd560, 0x10bea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x10bdc390)
        /cshome/odeke/goroot/src/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x10bdc390, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /cshome/odeke/goroot/src/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x10b27440)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:685 +0xab4

goroutine 46 [select]:
net/http.(*persistConn).writeLoop(0x10b27440)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:686 +0xad0

goroutine 50 [select]:
net/http.(*persistConn).writeLoop(0x10bce6c0)
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
        /cshome/odeke/goroot/src/go/src/net/http/transport.go:686 +0xad0`

**Comment by thindata** [comment]
Is this likely to get fixed?
