### ISSUE TITLE
Timeout error?

### ISSUE THREAD

**Issue by gfalken** [odeke-em/drive#546]
I received the following error trying to pull from a ~18GB directory. Any help would be appreciated.

pi@raspberrypi:/mnt/usbstorage/gdrive $ drive pull -no-prompt -ignore-name-clashes webs
Resolving...
unexpected fault address 0x62657743
fatal error: fault
[signal 0xb code=0x1 addr=0x62657743 pc=0x11b510]

goroutine 1 [running]:
runtime.throw(0x40ee88, 0x5)
	/home/pi/go/src/runtime/panic.go:527 +0x78 fp=0x10847bf0 sp=0x10847be4
runtime.sigpanic()
	/home/pi/go/src/runtime/sigpanic_unix.go:27 +0x280 fp=0x10847c1c sp=0x10847bf0
github.com/odeke-em/drive/src.(*Change).op(0x6265772f, 0x10)
	/home/pi/go/bin/src/github.com/odeke-em/drive/src/types.go:432 +0x30 fp=0x10847c34 sp=0x10847c20
github.com/odeke-em/drive/src.(*Change).Op(0x6265772f, 0x10)
	/home/pi/go/bin/src/github.com/odeke-em/drive/src/types.go:525 +0x38 fp=0x10847c40 sp=0x10847c34
github.com/odeke-em/drive/src.sift(0x1df3a000, 0x10c8f, 0x11000, 0x1aa40000, 0x6e10, 0x7800, 0x1c2691a0, 0x1, 0x2)
	/home/pi/go/bin/src/github.com/odeke-em/drive/src/changes.go:581 +0x90 fp=0x10847c80 sp=0x10847c40
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0x108c9620, 0x1df3a000, 0x10c8f, 0x11000, 0x11000, 0x0, 0x0)
	/home/pi/go/bin/src/github.com/odeke-em/drive/src/push.go:163 +0xac fp=0x10847d18 sp=0x10847c80
github.com/odeke-em/drive/src.pull(0x108c9620, 0x2, 0x0, 0x0)
	/home/pi/go/bin/src/github.com/odeke-em/drive/src/pull.go:111 +0x214 fp=0x10847dac sp=0x10847d18
github.com/odeke-em/drive/src.(*Commands).Pull(0x108c9620, 0x0, 0x0)
	/home/pi/go/bin/src/github.com/odeke-em/drive/src/pull.go:69 +0x30 fp=0x10847dc0 sp=0x10847dac
main.(*pullCmd).Run(0x108cbd40, 0x10884080, 0x1, 0x2, 0x108c8b60)
	/home/pi/go/bin/src/github.com/odeke-em/drive/cmd/drive/main.go:726 +0x74c fp=0x10847e9c sp=0x10847dc0
github.com/odeke-em/command.Run()
	/home/pi/go/bin/src/github.com/odeke-em/command/command.go:202 +0xac fp=0x10847ebc sp=0x10847e9c
github.com/odeke-em/command.ParseAndRun()
	/home/pi/go/bin/src/github.com/odeke-em/command/command.go:209 +0x18 fp=0x10847ec0 sp=0x10847ebc
main.main()
	/home/pi/go/bin/src/github.com/odeke-em/drive/cmd/drive/main.go:120 +0x2158 fp=0x10847f9c sp=0x10847ec0
runtime.main()
	/home/pi/go/src/runtime/proc.go:111 +0x2b4 fp=0x10847fc4 sp=0x10847f9c
runtime.goexit()
	/home/pi/go/src/runtime/asm_arm.s:1036 +0x4 fp=0x10847fc4 sp=0x10847fc4

goroutine 17 [syscall, 39 minutes, locked to thread]:
runtime.goexit()
	/home/pi/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 35 [syscall, 39 minutes]:
os/signal.loop()
	/home/pi/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
	/home/pi/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 18813 [IO wait]:
net.runtime_pollWait(0x749c5b58, 0x72, 0x10880000)
	/home/pi/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x1b0757f8, 0x72, 0x0, 0x0)
	/home/pi/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x1b0757f8, 0x0, 0x0)
	/home/pi/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x1b0757c0, 0x14e14000, 0x8000, 0x8000, 0x0, 0x749c0018, 0x10880000)
	/home/pi/go/src/net/fd_unix.go:232 +0x1c4
net.(*conn).Read(0x1a72a738, 0x14e14000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/pi/go/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x1afb1400, 0x74180158, 0x1a72a738, 0x5, 0x0, 0x0)
	/home/pi/go/src/crypto/tls/conn.go:455 +0xc8
crypto/tls.(*Conn).readRecord(0x1b014d00, 0x4b5417, 0x0, 0x0)
	/home/pi/go/src/crypto/tls/conn.go:540 +0x240
crypto/tls.(*Conn).Read(0x1b014d00, 0x17965000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/pi/go/src/crypto/tls/conn.go:901 +0x13c
net/http.noteEOFReader.Read(0x74184690, 0x1b014d00, 0x1b0138ec, 0x17965000, 0x1000, 0x1000, 0x227030, 0x0, 0x0)
	/home/pi/go/src/net/http/transport.go:1370 +0x5c
net/http.(*noteEOFReader).Read(0x1b1d01d0, 0x17965000, 0x1000, 0x1000, 0x1972f428, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0x1bd8a840)
	/home/pi/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x1bd8a840, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/pi/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x1b0138c0)
	/home/pi/go/src/net/http/transport.go:876 +0xe4
created by net/http.(*Transport).dialConn
	/home/pi/go/src/net/http/transport.go:685 +0xab4

goroutine 18814 [select]:
net/http.(*persistConn).writeLoop(0x1b0138c0)
	/home/pi/go/src/net/http/transport.go:1009 +0x314
created by net/http.(*Transport).dialConn
	/home/pi/go/src/net/http/transport.go:686 +0xad0
pi@raspberrypi:/mnt/usbstorage/gdrive $

**Comment by odeke-em** [comment]
Hello @gfalken. Thank you for reporting this issue and welcome to drive!

That looks like a slow internet connection tripped things out, from the stack trace and as you've mentioned.
If the directory is quite large, could you try pulling your content in small steps e.g
```shell
$ mkdir -p webs && cd webs
$ drive list
$ drive pull [target_paths...]
```

**Comment by gfalken** [comment]
That works but it kind of defeats the purpose of what I'm trying to do. I
want to run an unattended pull on my entire Google Drive (~40GB) every
night. The connection isn't that slow. Speedtest.net reports 19MB down and
3.5 up.

**Comment by odeke-em** [comment]
That is true, I hear ye.
I have a slow internet connection at home but am able to deal with large files, seems like a slow response time during the handshakes is what trips it out as you can see from the stack trace of the net/http code. However, I'll dig up on this in a couple of hours when am back home and got some free time.
