### ISSUE TITLE
panic: assertion failed: write: circular dependency occurred (drivedb)

### ISSUE THREAD

**Issue by thiell** [odeke-em/drive#607]
Hi @odeke-em,

I launch several `drive` processes in parallel, using `-piped` (each of them deals with a single file). It has been working fine until last night: I had to remove `.gd/drivedb` to continue using drive. I've copied the error and backtrace below. Is there a way to disable `.gd/drivedb` ? Not sure it's useful in my case.

(Please note that I'm not really using `cat file` but a process is dumping file content to stdout, that's just for the example)

```
$ cat file | drive push -piped -force /scratch/gdrive/17/04/60/0x200002585:0x11b74:0x0

panic: assertion failed: write: circular dependency occurred

goroutine 1 [running]:
github.com/boltdb/bolt._assert(0xc8201db600, 0x990c60, 0x23, 0x0, 0x0, 0x0)
	/test/go/src/github.com/boltdb/bolt/db.go:983 +0xee
github.com/boltdb/bolt.(*node).write(0xc8200b8c40, 0xc8201db000)
	/test/go/src/github.com/boltdb/bolt/node.go:221 +0x75f
github.com/boltdb/bolt.(*node).spill(0xc8200b8c40, 0x0, 0x0)
	/test/go/src/github.com/boltdb/bolt/node.go:373 +0x5bc
github.com/boltdb/bolt.(*Bucket).spill(0xc820438cc0, 0x0, 0x0)
	/test/go/src/github.com/boltdb/bolt/bucket.go:541 +0x1d9
github.com/boltdb/bolt.(*Bucket).spill(0xc82058e638, 0x0, 0x0)
	/test/go/src/github.com/boltdb/bolt/bucket.go:508 +0xb8a
github.com/boltdb/bolt.(*Tx).Commit(0xc82058e620, 0x0, 0x0)
	/test/go/src/github.com/boltdb/bolt/tx.go:163 +0x1d4
github.com/boltdb/bolt.(*DB).Update(0xc820500540, 0xc8200e55a0, 0x0, 0x0)
	/test/go/src/github.com/boltdb/bolt/db.go:580 +0x11d
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc820016f00, 0xc82001dc20, 0x0, 0x0)
	/test/go/src/github.com/odeke-em/drive/config/config.go:281 +0x18e
github.com/odeke-em/drive/src.(*Commands).remoteMkdirAll(0xc8200170c0, 0xc82019cc40, 0x13, 0x0, 0x0, 0x0)
	/test/go/src/github.com/odeke-em/drive/src/push.go:587 +0x912
github.com/odeke-em/drive/src.(*Commands).remoteMkdirAll(0xc8200170c0, 0xc8205681e0, 0x16, 0x0, 0x0, 0x0)
	/test/go/src/github.com/odeke-em/drive/src/push.go:554 +0x3ac
github.com/odeke-em/drive/src.(*Commands).PushPiped(0xc8200170c0, 0x0, 0x0)
	/test/go/src/github.com/odeke-em/drive/src/push.go:202 +0x61a
main.(*pushCmd).Run(0xc8200bebe0, 0xc82000a090, 0x1, 0x1, 0xc8200b5470)
	/test/go/src/github.com/odeke-em/drive/cmd/drive/main.go:797 +0x1ec
github.com/odeke-em/command.Run()
	/test/go/src/github.com/odeke-em/command/command.go:202 +0xaa
github.com/odeke-em/command.ParseAndRun()
	/test/go/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/test/go/src/github.com/odeke-em/drive/cmd/drive/main.go:123 +0x22b4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/golang/src/os/signal/signal_unix.go:28 +0x37

goroutine 27 [chan receive]:
github.com/odeke-em/drive/src.(*Remote).UpsertByComparison.func1(0xc820122480, 0xc82000fa00)
	/test/go/src/github.com/odeke-em/drive/src/remote.go:808 +0x45
created by github.com/odeke-em/drive/src.(*Remote).UpsertByComparison
	/test/go/src/github.com/odeke-em/drive/src/remote.go:811 +0x208

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7fc49c284598, 0x72, 0xc8200101e0)
	/usr/lib/golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200d6450, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200d6450, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200d63f0, 0xc8202f9000, 0x1000, 0x1000, 0x0, 0x7fc49c27a050, 0xc8200101e0)
	/usr/lib/golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002e3a8, 0xc8202f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82029fef0, 0x7fc49c2849e0, 0xc82002e3a8, 0x5, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820081080, 0x9e5117, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820081080, 0xc82001b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fc49c28a2a0, 0xc820081080, 0xc820014268, 0xc82001b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820129ba0, 0xc82001b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82001d3e0)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82001d3e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820014210)
	/usr/lib/golang/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:685 +0xc78

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc820014210)
	/usr/lib/golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:686 +0xc9d

goroutine 25 [IO wait]:
net.runtime_pollWait(0x7fc49c284658, 0x72, 0xc8200101e0)
	/usr/lib/golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200b2220, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200b2220, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200b21c0, 0xc8201a0000, 0x1000, 0x1000, 0x0, 0x7fc49c27a050, 0xc8200101e0)
	/usr/lib/golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002e040, 0xc8201a0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201764e0, 0x7fc49c2849e0, 0xc82002e040, 0x5, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200818c0, 0x9e5117, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8200818c0, 0xc8201b8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fc49c28a2a0, 0xc8200818c0, 0xc8204e3e98, 0xc8201b8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8201a3b00, 0xc8201b8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8201b6180)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201b6180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8204e3e40)
	/usr/lib/golang/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:685 +0xc78

goroutine 26 [select]:
net/http.(*persistConn).writeLoop(0xc8204e3e40)
	/usr/lib/golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:686 +0xc9d
```

```
$ drive version
drive version: 0.3.5
Commit Hash: '062afd48c6532c8219ccf6c3af147cec83b0aab8'
Go Version: go1.5.1
OS: linux/amd64
BuildTime: 2016
-03-23 11:44:04.548959235 -0700 PDT
```
Thanks!

**Comment by odeke-em** [comment]
Hello again @thiell, thanks for reporting this.

Unfortunately I've never encountered this error. Would you mind opening an issue at the BoltDB home here https://github.com/boltdb/bolt? This is because you have more context about the problem and might be able to reproduce it.

Actually the db is needed to keep information(in the form of indices) about files since last pull/push for example to figure out if there are conflicts in files, whether a file needs modification and other information to avoid spurious uploads/downloads. Before index files were stored on disk but that would caused lots of files locally. We could potentially look at re-allowing storing to disk instead of to a DB or making a common interface to plug into any kind of storage.

**Comment by thiell** [comment]
Thanks @odeke-em for the quick reply and the precious information. I may have find the issue: I'm using Lustre as filesystem (where the .gd/drivedb is stored) and it wasn't mounted with the right `flock` option (only with `localflock` but the behavior is not the same), and I guess boltdb makes use of flock to soft-lock the drivedb file. I only have the problem when using several lustre clients, so I guess that's it. I'm running it right now with flock and will continue during the week-end so I can see if the problem is gone. If not, I iwll open a bolt ticket. Will see!

**Comment by odeke-em** [comment]
Wow, this cool to know, I had never encountered anyone using Lustre. If I may ask supercomputers? Awesome, good to know you diagnosed the issue.

**Comment by thiell** [comment]
Hi @odeke-em,
Yes, HPC clusters, doing some tests... ;)
I confirm I don't see the problem anymore using the proper flock mount option when using Lustre. 
Thanks!
