### ISSUE TITLE
spanic: runtime error: invalid memory address or nil pointer !

### ISSUE THREAD

**Issue by Jedtek** [odeke-em/drive#625]
Hi,

I have already read through the reports previous for this error but think mine is a different issue. I have a cron job that uses drive-google to push a zip file ranging from 4-15gb usually that is pushed up once a day overwriting the previous version of itself on the Drive account. It seems sometimes it works and sometimes I get an exception like the following:

```
461373440 / 304691751!  14.87 % 6m16s
914358272 / 3046917517  30.!3 % 5m10s
1358954496 / 3046917517  44!33 % 4m12s
1786773504 / 3046917517  58.64 % 3m2

spanic: runtime error: invalid memory address or nil pointer !
 dereference
[signal 0xb code=0x1 addr=0x10 pc=0x6613ee]

goroutine 31 [running]:
google.golang.org/api/gensupport.(*ResumableUpload).transferChunks(0xc820118300, 0x7ff38104e690, 0xc820010550, 0xc820dc1b80, 0x0, 0x0)
        /root/gopath/src/google.golang.org/api/gensupport/resumable.go:89 +0x61e                                                            
google.golang.org/api/gensupport.(*ResumableUpload).Upload(0xc820118300, 0x7ff38104e690, 0xc820010550, 0xc82013c000, 0x0, 0x0)
	/root/gopath/src/google.golang.org/api/gensupport/resumable.go:114 +0x5e
google.golang.org/api/drive/v2.(*FilesInsertCall).Do(0xc8201181e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/gopath/src/google.golang.org/api/drive/v2/drive-gen.go:5534 +0x546
github.com/odeke-em/drive/src.(*Remote).upsertByComparison(0xc82000f560, 0x7ff3800155a8, 0xc820497720, 0xc82045d500, 0x0, 0x1, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/remote.go:687 +0x531
github.com/odeke-em/drive/src.(*Remote).UpsertByComparison.func2.1(0x0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/remote.go:817 +0xa7
github.com/odeke-em/exponential-backoff.ExponentialBackOffSync.func1(0xc820427860, 0xc820497760)
	/root/gopath/src/github.com/odeke-em/exponential-backoff/exponential-backoff.go:34 +0x78
created by github.com/odeke-em/exponential-backoff.ExponentialBackOffSync
	/root/gopath/src/github.com/odeke-em/exponential-backoff/exponential-backoff.go:52 +0x7c

goroutine 1 [chan receive, 4 minutes]:
github.com/odeke-em/drive/src.(*Commands).playPushChanges(0xc82000b100, 0xc820104080, 0x1, 0x1, 0xc8200fd860, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/push.go:317 +0x361
github.com/odeke-em/drive/src.(*Commands).Push(0xc82000b100, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/push.go:152 +0x16aa
main.(*pushCmd).Run(0xc8200bebe0, 0xc82000a1b0, 0x1, 0x1, 0xc8200b3440)
	/root/gopath/src/github.com/odeke-em/drive/drive-google/main.go:799 +0x237
github.com/odeke-em/command.Run()
	/root/gopath/src/github.com/odeke-em/command/command.go:202 +0xaa
github.com/odeke-em/command.ParseAndRun()
	/root/gopath/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/root/gopath/src/github.com/odeke-em/drive/drive-google/main.go:123 +0x22b4

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall, 4 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, 4 minutes, locked to thread]:
runtime.gopark(0x9e7dd0, 0xc820020728, 0x911308, 0x6, 0x441918, 0x2)                                                                        
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820020728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820020728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 7 [chan receive, 4 minutes]:
github.com/odeke-em/drive/src.(*Commands).Push.func1(0xc8200c2300, 0xc82000f860, 0xc82000b100)
	/root/gopath/src/github.com/odeke-em/drive/src/push.go:52 +0x43
created by github.com/odeke-em/drive/src.(*Commands).Push
	/root/gopath/src/github.com/odeke-em/drive/src/push.go:56 +0x335

goroutine 27 [chan receive, 4 minutes]:
github.com/odeke-em/semalim.Run.func5(0xc820427440, 0xc820427560, 0xc8204274a0)
	/root/gopath/src/github.com/odeke-em/semalim/semalim.go:90 +0xc8
created by github.com/odeke-em/semalim.Run
	/root/gopath/src/github.com/odeke-em/semalim/semalim.go:92 +0x24f

goroutine 23 [select]:
github.com/cheggaaa/pb.(*ProgressBar).writer(0xc8203f9400)
	/root/gopath/src/github.com/cheggaaa/pb/pb.go:375 +0x111
created by github.com/cheggaaa/pb.(*ProgressBar).Start
	/root/gopath/src/github.com/cheggaaa/pb/pb.go:113 +0xa9

goroutine 24 [chan receive]:
github.com/odeke-em/drive/src.(*Commands).playPushChanges.func1(0xc82000b100)
	/root/gopath/src/github.com/odeke-em/drive/src/push.go:271 +0x49
created by github.com/odeke-em/drive/src.(*Commands).playPushChanges
	/root/gopath/src/github.com/odeke-em/drive/src/push.go:274 +0x1e6

goroutine 28 [chan receive, 4 minutes]:
github.com/odeke-em/drive/src.(*Remote).UpsertByComparison(0xc82000f560, 0xc82045d500, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/remote.go:827 +0x299
github.com/odeke-em/drive/src.(*Commands).remoteMod(0xc82000b100, 0xc820472440, 0x0, 0x0)
        /root/gopath/src/github.com/odeke-em/drive/src/push.go:438 +0x839                                                                   
github.com/odeke-em/drive/src.(*Commands).remoteAdd(0xc82000b100, 0xc820472440, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/push.go:457 +0x39
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.remoteAdd)-fm(0xc820472440, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/misc.go:1032 +0x38
github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0x0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/misc.go:120 +0x23e
github.com/odeke-em/drive/src.jobSt.Do(0x0, 0xc820496f20, 0x0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/drive/src/misc.go:100 +0x35
github.com/odeke-em/drive/src.(*jobSt).Do(0xc820475b50, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:4 +0xb0
github.com/odeke-em/semalim.Run.func4.1(0xc820475b10, 0xc820427440, 0xc820475b20, 0xc820475b30, 0x7ff380015488, 0xc820475b50)
	/root/gopath/src/github.com/odeke-em/semalim/semalim.go:71 +0x46
created by github.com/odeke-em/semalim.Run.func4
	/root/gopath/src/github.com/odeke-em/semalim/semalim.go:76 +0x12c

goroutine 29 [chan receive]:
github.com/odeke-em/drive/src.(*Remote).UpsertByComparison.func1(0xc820497720, 0xc82000f560)
	/root/gopath/src/github.com/odeke-em/drive/src/remote.go:808 +0x45
created by github.com/odeke-em/drive/src.(*Remote).UpsertByComparison
	/root/gopath/src/github.com/odeke-em/drive/src/remote.go:811 +0x208

goroutine 30 [runnable]:
github.com/odeke-em/exponential-backoff.ExponentialBackOffSync(0xc820497760, 0x0, 0x0, 0x0, 0x0)
	/root/gopath/src/github.com/odeke-em/exponential-backoff/exponential-backoff.go:54 +0xa9
github.com/odeke-em/drive/src.(*Remote).UpsertByComparison.func2(0xc82000f560, 0xc820497720, 0xc82045d500, 0xc820427800)
	/root/gopath/src/github.com/odeke-em/drive/src/remote.go:823 +0x12b
created by github.com/odeke-em/drive/src.(*Remote).UpsertByComparison
	/root/gopath/src/github.com/odeke-em/drive/src/remote.go:825 +0x26c
```

Diagnostic Info:
```
root@broadside:~/gopath/src/github.com/odeke-em/drive# go version
go version go1.5.3 linux/amd64

root@broadside:~/gopath/src/github.com/odeke-em/drive# git log | head -n 20
commit 9ba58541a7a40675f389bdad3da303b6140a059c
Merge: ace8b89 6b19f7c
Author: Emmanuel Odeke <emm.odeke@gmail.com>
Date:   Tue Jan 19 07:19:51 2016 -0700

    Merge branch 'pptx-mimeType-correction'

commit 6b19f7cc144d0bede609eba6e55a2271917c166c
Author: Emmanuel Odeke <emm.odeke@gmail.com>
Date:   Tue Jan 19 07:17:06 2016 -0700

    pptx mimeType corrected
    
    Fixes #551.
    
    Ensures that the proper mimeType is used for pptx files
    since before the format was that of `open ms-powerpoint`
    yet it is `openxmlformats-officedocument.presentationml.presentation`.

commit ace8b899064e2eeed275620ebc98ed26144dd734
```

I hope you can give me a better idea than what I can come up with so my script can work 100% of the time. :)

Thanks,
Jed.

**Comment by odeke-em** [comment]
Hello there @Jedtek, thank you for the report and welcome to drive.
For starters please get the latest code by running
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
a bunch of fixes have gone in since January and the latest is at
```shell
commit 3385bd27a98da1d9f27333b015b4e520cbd06f2a
Merge: 8c4ba8e dd3580c
Author: Emmanuel T Odeke <odeke@ualberta.ca>
Date:   Sun Apr 17 23:50:30 2016 -0700

    Merge pull request #623 from thiell/master
    
    push -piped: return error in case of remoteMkdirAll failure

commit dd3580c15c2b7d8f0571b4a88b5396c7f1fa9e81
Author: Stephane Thiell <sthiell@stanford.edu>
Date:   Sun Apr 17 16:05:20 2016 -0700

    push -piped: return error in case of remoteMkdirAll failure
```
