### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by DunklerPhoenix** [odeke-em/drive#745]
Hello.
Since one week I get this error. I tried to reinstall go and the drive client.
What can I do to fix this?

```
Addition count 64731 src: 1.74TB
Proceed with the changes? [Y/n]:Y
 1024 / 1917849953769 [>-----------------------------------------------------------------------]   0.00% -2500288h47m5spanic: send on closed channel [recovered]
    panic: send on closed channel

goroutine 78859 [running]:
panic(0x8289c0, 0xc8255a0710)
    /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
io/ioutil.readAll.func1(0xc824763b48)
    /usr/lib/go-1.6/src/io/ioutil/ioutil.go:30 +0x11e
panic(0x8289c0, 0xc8255a0710)
    /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/odeke-em/statos.(*ReaderStatos).Read(0xc82ef99c40, 0xc820146400, 0x200, 0x200, 0x200, 0x0, 0x0)
    /root/go/src/github.com/odeke-em/statos/reader.go:34 +0x119
io.(*LimitedReader).Read(0xc82ef99360, 0xc820146400, 0x200, 0x200, 0x200, 0x0, 0x0)
    /usr/lib/go-1.6/src/io/io.go:426 +0xbd
bytes.(*Buffer).ReadFrom(0xc824763aa0, 0x7fdb8849d1d0, 0xc82ef99360, 0x0, 0x0, 0x0)
    /usr/lib/go-1.6/src/bytes/buffer.go:176 +0x23f
io/ioutil.readAll(0x7fdb8849d1d0, 0xc82ef99360, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go-1.6/src/io/ioutil/ioutil.go:33 +0x156
io/ioutil.ReadAll(0x7fdb8849d1d0, 0xc82ef99360, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go-1.6/src/io/ioutil/ioutil.go:42 +0x51
google.golang.org/api/gensupport.(*contentSniffer).ContentType(0xc8242b25a0, 0x0, 0x0, 0xc824763c80)
    /root/go/src/google.golang.org/api/gensupport/media.go:61 +0x125
google.golang.org/api/gensupport.DetermineContentType(0x7fdb84320238, 0xc82ef99c40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /root/go/src/google.golang.org/api/gensupport/media.go:94 +0x198
google.golang.org/api/drive/v2.(*FilesInsertCall).Media(0xc82557a8a0, 0x7fdb84320238, 0xc82ef99c40, 0x0, 0x0, 0x0, 0xc800000000)
    /root/go/src/google.golang.org/api/drive/v2/drive-gen.go:5590 +0x8e
github.com/odeke-em/drive/src.(*Remote).upsertByComparison(0xc8200d7ce0, 0x7fdb84320238, 0xc82ef99c40, 0xc8230f1880, 0x0, 0xaad800, 0x0, 0x0)
    /root/go/src/github.com/odeke-em/drive/src/remote.go:762 +0x5ad
github.com/odeke-em/drive/src.(*Remote).UpsertByComparison.func2.1(0x0, 0x0, 0x0, 0x0)
    /root/go/src/github.com/odeke-em/drive/src/remote.go:916 +0xa7
github.com/odeke-em/exponential-backoff.ExponentialBackOffSync.func1(0xc82557b920, 0xc82ef99c80)
    /root/go/src/github.com/odeke-em/exponential-backoff/exponential-backoff.go:34 +0x71
created by github.com/odeke-em/exponential-backoff.ExponentialBackOffSync
    /root/go/src/github.com/odeke-em/exponential-backoff/exponential-backoff.go:52 +0x7c
```

`

**Comment by odeke-em** [comment]
Hello there @DunklerPhoenix, thank you for reporting this issue and welcome to drive.

My apologies for the late reply, I hadn't seen this.

So for starters what does your `drive version` say?

**Comment by DunklerPhoenix** [comment]
```
drive version
drive version: 0.3.8
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 
```

**Comment by odeke-em** [comment]
@DunklerPhoenix my apologies that I haven't been able to address this any sooner. I've been quiet busy but tonight I took sometime to fix up and refactor a dependency from which the panic originates with PR https://github.com/odeke-em/statos/pull/2.
Please get the latest code by running
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
