### ISSUE TITLE
git pull panics above high water mark

### ISSUE THREAD

**Issue by skrzepto** [odeke-em/drive#824]
I was doing my initial git pull for my drive and in the middle of pulling it panics. I tried to rerun drive pull and it constantly panics with the same error.

log

```
 3194928566 / 5372734489 [======================================================>------------------------------------]  59.47% 2h6m14s

panic: pgid (68719476737) above high water mark (114)

goroutine 1857 [running]:
panic(0x931900, 0xc8203aa9b0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/boltdb/bolt.(*node).spill(0xc820d5ae00, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/boltdb/bolt/node.go:375 +0x54e
github.com/boltdb/bolt.(*node).spill(0xc820d5ad20, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/boltdb/bolt/node.go:350 +0x12c
github.com/boltdb/bolt.(*node).spill(0xc820d5ac40, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/boltdb/bolt/node.go:350 +0x12c
github.com/boltdb/bolt.(*Bucket).spill(0xc820418638, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/boltdb/bolt/bucket.go:570 +0x1cf
github.com/boltdb/bolt.(*Tx).Commit(0xc820418620, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/boltdb/bolt/tx.go:163 +0x1d4
github.com/boltdb/bolt.(*DB).Update(0xc8201ea780, 0xc8204f9b70, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/boltdb/bolt/db.go:605 +0x11d
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc8201ce0c0, 0xc820923920, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/odeke-em/drive/config/config.go:279 +0x1a3
github.com/odeke-em/drive/src.(*Commands).createIndex(0xc8201ce2c0, 0xc8200f4840, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/odeke-em/drive/src/fetch.go:314 +0x1df
github.com/odeke-em/drive/src.(*Commands).localAdd.func1(0xc8204f9d50, 0xc82064da80, 0xc8201ce2c0)
	/home/skrzepto/go/src/github.com/odeke-em/drive/src/pull.go:574 +0x65
github.com/odeke-em/drive/src.(*Commands).localAdd(0xc8201ce2c0, 0xc82064da80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/odeke-em/drive/src/pull.go:605 +0x2b1
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.localAdd)-fm(0xc82064da80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/odeke-em/drive/src/misc.go:1066 +0x56
github.com/odeke-em/drive/src.(*Commands).playPullChanges.func2.1(0xc82064da80, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/odeke-em/drive/src/pull.go:477 +0x57
github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0x0, 0x0, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/odeke-em/drive/src/misc.go:120 +0x23e
github.com/odeke-em/drive/src.jobSt.Do(0x4ac, 0xc8202555a0, 0x0, 0x0, 0x0, 0x0)
	/home/skrzepto/go/src/github.com/odeke-em/drive/src/misc.go:100 +0x35
github.com/odeke-em/drive/src.(*jobSt).Do(0xc820ac9390, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:6 +0xb0
github.com/odeke-em/semalim.Run.func4.1(0xc8202664f0, 0xc82064f140, 0xc820266560, 0xc8202665d0, 0x7fdf10af0668, 0xc820ac9390)
	/home/skrzepto/go/src/github.com/odeke-em/semalim/semalim.go:71 +0x46
created by github.com/odeke-em/semalim.Run.func4
	/home/skrzepto/go/src/github.com/odeke-em/semalim/semalim.go:76 +0x12c
```

**Comment by odeke-em** [comment]
Hello there @skrzepto, thank you for the issue and welcome to drive!

I've never seen that error. Looks like a boltdb trip, time to investigate it.

Might you have a way of reproducing it?
Also what does `drive version` say?

**Comment by skrzepto** [comment]
Hey @odeke-em here's the output
```
➜  ~ drive-google version
drive version: 0.3.8.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 
```

**Comment by nelaaro** [comment]
Hi Odeke-em

I am having the same issues.

Let me know if I can provide any additional info or to test any patches.

My error messages is slightly different. 
"above high water mark (16)"

$ drive version
drive version: 0.3.9
Commit Hash: 'be79a211364f0e0b8f83998eb2c4551577a25dbd'
Go Version: go1.6.3
OS: linux/amd64
BuildTime: 2017-01-06 11:56:47.061799208 +0200 SAST

```
$ drive pull
Resolving...
panic: pgid (68719476737) above high water mark (16)

goroutine 1 [running]:
panic(0x55e3c4ecc000, 0xc820abf420)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/boltdb/bolt.(*node).spill(0xc82070aaf0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:375 +0x54e
github.com/boltdb/bolt.(*node).spill(0xc82070aa10, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:350 +0x12c
github.com/boltdb/bolt.(*Bucket).spill(0xc8202fa0f8, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/bucket.go:570 +0x1cf
github.com/boltdb/bolt.(*Tx).Commit(0xc8202fa0e0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/tx.go:163 +0x1d4
github.com/boltdb/bolt.(*DB).Update(0xc82020c000, 0xc820147648, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/db.go:605 +0x11d
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket(0xc8201e6000, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:255 +0xb5
github.com/odeke-em/drive/config.(*Context).DeserializeIndex(0xc8201e6000, 0xc820469360, 0x1c, 0x0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:115 +0x4e
github.com/odeke-em/drive/src.(*Commands).deserializeIndex(0xc8201e6200, 0xc820469360, 0x1c, 0xc820478000)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/push.go:243 +0x38
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.deserializeIndex)-fm(0xc820469360, 0x1c, 0x2)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/changes.go:719 +0x34
github.com/odeke-em/drive/src.resolveConflicts(0xc8201f1e80, 0x8, 0x8, 0xc820c14a00, 0xc8201478f0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/changes.go:700 +0x135
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc8201e6200, 0xc820c10500, 0x84c, 0x8a0, 0x800, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/changes.go:719 +0x1df
github.com/odeke-em/drive/src.pull(0xc8201e6200, 0x2, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/pull.go:116 +0x41b
github.com/odeke-em/drive/src.(*Commands).Pull(0xc8201e6200, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/pull.go:71 +0x36
main.(*pullCmd).Run(0xc8201e4000, 0xc82000a2b0, 0x0, 0x0, 0xc8201da5a0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:789 +0xae3
github.com/odeke-em/command.Run()
	/home/aaron/lib/golang/src/github.com/odeke-em/command/command.go:202 +0xaa
github.com/odeke-em/command.ParseAndRun()
	/home/aaron/lib/golang/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x22d7
```

```
drive pull
Resolving...
panic: pgid (68719476737) above high water mark (16)

goroutine 1 [running]:
panic(0x55b72850a000, 0xc820484340)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/boltdb/bolt.(*node).spill(0xc82078ebd0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:375 +0x54e
github.com/boltdb/bolt.(*node).spill(0xc82078eb60, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:350 +0x12c
github.com/boltdb/bolt.(*Bucket).spill(0xc8203aeb78, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/bucket.go:570 +0x1cf
github.com/boltdb/bolt.(*Tx).Commit(0xc8203aeb60, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/tx.go:163 +0x1d4
github.com/boltdb/bolt.(*DB).Update(0xc820220000, 0xc820159648, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/db.go:605 +0x11d
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket(0xc820015f40, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:255 +0xb5
github.com/odeke-em/drive/config.(*Context).DeserializeIndex(0xc820015f40, 0xc820461440, 0x1c, 0x0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:115 +0x4e
github.com/odeke-em/drive/src.(*Commands).deserializeIndex(0xc8201fa140, 0xc820461440, 0x1c, 0xc82002ec00)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/push.go:243 +0x38
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.deserializeIndex)-fm(0xc820461440, 0x1c, 0x2)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/changes.go:719 +0x34
github.com/odeke-em/drive/src.resolveConflicts(0xc820676a80, 0x8, 0x8, 0xc820936a00, 0xc8201598f0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/changes.go:700 +0x135
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc8201fa140, 0xc820932500, 0x84c, 0x8a0, 0x800, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/changes.go:719 +0x1df
github.com/odeke-em/drive/src.pull(0xc8201fa140, 0x2, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/pull.go:116 +0x41b
github.com/odeke-em/drive/src.(*Commands).Pull(0xc8201fa140, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/pull.go:71 +0x36
main.(*pullCmd).Run(0xc8201f6000, 0xc820096070, 0x0, 0x0, 0xc8201dbc20)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:789 +0xae3
github.com/odeke-em/command.Run()
	/home/aaron/lib/golang/src/github.com/odeke-em/command/command.go:202 +0xaa
github.com/odeke-em/command.ParseAndRun()
	/home/aaron/lib/golang/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x22d7
```

```
drive pull -force
....
  Addition count 2216 src: 1.56GB dest: 64.38MB
  Deletion count 8 dest: 1.60KB
  Modification count 8 src: 19.34MB
  Proceed with the changes? [Y/n]:y
   1634 / 1694636029 [>--------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 17d41m38spanic: pgid (68719476737) above high water mark (16)

  goroutine 1348 [running]:
  panic(0x5607bb1c1000, 0xc820c167d0)
  	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
  github.com/boltdb/bolt.(*node).spill(0xc820b82620, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:375 +0x54e
  github.com/boltdb/bolt.(*node).spill(0xc820b825b0, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:350 +0x12c
  github.com/boltdb/bolt.(*Bucket).spill(0xc8203a08d8, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/boltdb/bolt/bucket.go:570 +0x1cf
  github.com/boltdb/bolt.(*Tx).Commit(0xc8203a08c0, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/boltdb/bolt/tx.go:163 +0x1d4
  github.com/boltdb/bolt.(*DB).Update(0xc8201881e0, 0xc820c47b80, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/boltdb/bolt/db.go:605 +0x11d
  github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc820015b80, 0xc8208d36e0, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:279 +0x1a3
  github.com/odeke-em/drive/src.(*Commands).createIndex(0xc820015cc0, 0xc82059e2c0, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/fetch.go:314 +0x1df
  github.com/odeke-em/drive/src.(*Commands).localMod.func1(0xc820c47d40, 0xc8205cdf00, 0xc820015cc0)
  	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/pull.go:528 +0x56
  github.com/odeke-em/drive/src.(*Commands).localMod(0xc820015cc0, 0xc8205cdf00, 0x0, 0x0, 0x0, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/pull.go:566 +0x2af
  github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.localMod)-fm(0xc8205cdf00, 0x0, 0x0, 0x0, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/misc.go:1062 +0x56
  github.com/odeke-em/drive/src.(*Commands).playPullChanges.func2.1(0xc8205cdf00, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/pull.go:477 +0x57
  github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0x0, 0x0, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/misc.go:120 +0x23e
  github.com/odeke-em/drive/src.jobSt.Do(0x8, 0xc820c34560, 0x0, 0x0, 0x0, 0x0)
  	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/misc.go:100 +0x35
  github.com/odeke-em/drive/src.(*jobSt).Do(0xc820b81d30, 0x0, 0x0, 0x0, 0x0)
  	<autogenerated>:6 +0xb0
  github.com/odeke-em/semalim.Run.func4.1(0xc8206beb90, 0xc8207c6480, 0xc8206beba0, 0xc8206bebb0, 0x7f3a8cfea928, 0xc820b81d30)
  	/home/aaron/lib/golang/src/github.com/odeke-em/semalim/semalim.go:71 +0x46
  created by github.com/odeke-em/semalim.Run.func4
  	/home/aaron/lib/golang/src/github.com/odeke-em/semalim/semalim.go:76 +0x12c
```


```
$ drive index -prune
panic: pgid (68719476737) above high water mark (16)

goroutine 1 [running]:
panic(0x55c636801000, 0xc8201f6a40)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/boltdb/bolt.(*node).spill(0xc8201f9960, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:375 +0x54e
github.com/boltdb/bolt.(*node).spill(0xc8201f98f0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:350 +0x12c
github.com/boltdb/bolt.(*Bucket).spill(0xc8201701d8, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/bucket.go:570 +0x1cf
github.com/boltdb/bolt.(*Tx).Commit(0xc8201701c0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/tx.go:163 +0x1d4
github.com/boltdb/bolt.(*DB).Update(0xc8201781e0, 0xc8201499e8, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/db.go:605 +0x11d
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket(0xc820153440, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:255 +0xb5
github.com/odeke-em/drive/config.(*Context).ListKeys(0xc820153440, 0xc8201f5260, 0x24, 0x55c636a11770, 0x7, 0x55c6362db642, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:153 +0x5a
github.com/odeke-em/drive/src.(*Commands).listIndicesKeys(0xc820153600, 0xc820156478, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/fetch.go:222 +0x84
github.com/odeke-em/drive/src.(*Commands).pruneStaleIndices(0xc820153600, 0x0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/fetch.go:227 +0x56
github.com/odeke-em/drive/src.(*Commands).Prune(0xc820153600, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/fetch.go:39 +0x56
github.com/odeke-em/drive/src.(*Commands).Prune-fm(0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:602 +0x2e
main.(*indexCmd).Run(0xc82015a680, 0xc8200741d0, 0x0, 0x0, 0xc8201f4cf0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:610 +0x40f
github.com/odeke-em/command.Run()
	/home/aaron/lib/golang/src/github.com/odeke-em/command/command.go:202 +0xaa
github.com/odeke-em/command.ParseAndRun()
	/home/aaron/lib/golang/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x22d7
aaron@aaron-ubunix:~/Documents/gdrive/nelaaro
```

```
$ drive index -all-ops
panic: pgid (68719476737) above high water mark (16)

goroutine 1 [running]:
panic(0x5562ce648000, 0xc8201ea070)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/boltdb/bolt.(*node).spill(0xc8201dcbd0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:375 +0x54e
github.com/boltdb/bolt.(*node).spill(0xc8201dcb60, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/node.go:350 +0x12c
github.com/boltdb/bolt.(*Bucket).spill(0xc82013c398, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/bucket.go:570 +0x1cf
github.com/boltdb/bolt.(*Tx).Commit(0xc82013c380, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/tx.go:163 +0x1d4
github.com/boltdb/bolt.(*DB).Update(0xc82017c1e0, 0xc8201459e8, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/boltdb/bolt/db.go:605 +0x11d
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket(0xc82006ffc0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:255 +0xb5
github.com/odeke-em/drive/config.(*Context).ListKeys(0xc82006ffc0, 0xc8201d35f0, 0x24, 0x5562ce858770, 0x7, 0x5562ce122642, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/config/config.go:153 +0x5a
github.com/odeke-em/drive/src.(*Commands).listIndicesKeys(0xc8201e4180, 0xc820094510, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/fetch.go:222 +0x84
github.com/odeke-em/drive/src.(*Commands).pruneStaleIndices(0xc8201e4180, 0x0, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/fetch.go:227 +0x56
github.com/odeke-em/drive/src.(*Commands).Prune(0xc8201e4180, 0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/src/fetch.go:39 +0x56
github.com/odeke-em/drive/src.(*Commands).Prune-fm(0x0, 0x0)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:602 +0x2e
main.(*indexCmd).Run(0xc82009c980, 0xc8200741d0, 0x0, 0x0, 0xc8201d3080)
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:610 +0x40f
github.com/odeke-em/command.Run()
	/home/aaron/lib/golang/src/github.com/odeke-em/command/command.go:202 +0xaa
github.com/odeke-em/command.ParseAndRun()
	/home/aaron/lib/golang/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/home/aaron/lib/golang/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x22d7
```

**Comment by odeke-em** [comment]
Hey folks, I just commented at https://github.com/odeke-em/drive/issues/839#issuecomment-271697335. Please use that boltdb commit so that we'll be at par. You can do so like this:

```shell
$ cd $GOPATH/src/github.com/boltdb/bolt && git reset --hard 852d3024fa8d89dcc9a715bab6f4dcd7d59577dd
$ drive-gen
```

**Comment by nelaaro** [comment]
@odeke-em 

I have finished the wiki on how to work around this problem. 
 https://github.com/odeke-em/drive/wiki/Boltdb-breaks-drive-with-(panic:-invalid-page-type:)-or-(panic:--above-high-water-mark)

**Comment by odeke-em** [comment]
Thank you very much @nelaaro!

**Comment by lexo13** [comment]
the same for me on kubuntu 16.04

drive version 
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime:

drive pull                                                                                                                                                            
Resolving...
panic: pgid (68719476737) above high water mark (35)

goroutine 1 [running]:
panic(0x55e5a9d15da0, 0xc4203ed920)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*node).spill(0xc4203b53b0, 0xc4203846a0, 0xc4203846a0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/node.go:375 +0x616
github.com/boltdb/bolt.(*node).spill(0xc4203b5340, 0x10, 0x10)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/node.go:350 +0xb7
github.com/boltdb/bolt.(*Bucket).spill(0xc4203a4718, 0x55e537ba000d, 0x55e5aa23c540)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/bucket.go:570 +0x43b
github.com/boltdb/bolt.(*Tx).Commit(0xc4203a4700, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/boltdb/bolt.(*DB).Update(0xc42012a5a0, 0x55e5a9e224a8, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/db.go:605 +0x10d
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket(0xc42001b080, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/config/config.go:255 +0xaf
github.com/odeke-em/drive/config.(*Context).DeserializeIndex(0xc42001b080, 0xc420438420, 0x1c, 0x0, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/config/config.go:115 +0x64
github.com/odeke-em/drive/src.(*Commands).deserializeIndex(0xc42001b100, 0xc420438420, 0x1c, 0xc4201a5978)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/push.go:244 +0x42
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.deserializeIndex)-fm(0xc420438420, 0x1c, 0x55e5a9d08ee0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/changes.go:719 +0x3e
github.com/odeke-em/drive/src.resolveConflicts(0xc420347740, 0x5, 0x8, 0xc420468c00, 0xc4201a5a90, 0x80, 0xc420347740, 0x5, 0x8, 0x55e5a995e935, ...)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/changes.go:700 +0x104
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc42001b100, 0xc42065a000, 0x63, 0x70, 0x0, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/changes.go:719 +0x1c0
github.com/odeke-em/drive/src.pull(0xc42001b100, 0x2, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:117 +0x2e0
github.com/odeke-em/drive/src.(*Commands).Pull(0xc42001b100, 0xc42000ae00, 0xc42001b100)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:71 +0x34
main.(*pullCmd).Run(0xc4200d22d0, 0xc42000c450, 0x0, 0x0, 0xc42017a0f0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/cmd/drive/main.go:797 +0x9cd
github.com/odeke-em/command.Run()
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/command/command.go:202 +0x81
github.com/odeke-em/command.ParseAndRun()
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x1968

**Comment by odeke-em** [comment]
Hey folks, please get and test out the latest boltdb as per https://github.com/boltdb/bolt/pull/654
You can do so by running
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
and let me know if the problem persists and I'll report back to the boltdb issue.

**Comment by shaggytwodope** [comment]
@odeke-em if reports are solid, should I rebuild with this revision of bolt? Not sure if anyones reported issues with ppa packages and such.

**Comment by odeke-em** [comment]
Idk if the problem is fixed, I've never encountered it so can't tell. I'll have to wait for feedback from the folks who reported it.

**Comment by mwensveen-nl** [comment]
I'm having the same issue. Trying the solution described by odeke-em:
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
gives me this error

github.com/odeke-em/drive/drive-gen/build.go:24: syntax error: unexpected string literal, expecting comma or )

**Comment by scmbradley** [comment]
@shaggytwodope I'm getting this error using your ppa version of drive.

**Comment by shaggytwodope** [comment]
@mwensveen-nl are you using the right version of go? currently only supported version is 1.7.

**Comment by shaggytwodope** [comment]
@scmbradley the ppa is being updated as I'm typing this. New version will be available shortly including this fix. It'll take up to an hour to update all ubuntu versions. Any errors or issues just fire a report here for lord @odeke-em. (I made him a lord now :-p)

**Comment by mwensveen-nl** [comment]
@shaggytwodope I'm not at work anymore. I'll have to check Monday. But I guess I can get the new version from the PPA by thank. Thanks.

**Comment by mwensveen-nl** [comment]
@shaggytwodope I am afraid I still get the error on a drive-push
Resolving...
panic: pgid (68719476737) above high water mark (21)

goroutine 1 [running]:
panic(0x8a74a0, 0xc42043e150)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*node).spill(0xc42016a150, 0xc420438120, 0xc420438120)
	/home/user/go/src/github.com/boltdb/bolt/node.go:375 +0x616
github.com/boltdb/bolt.(*node).spill(0xc42016a070, 0x10, 0x10)
	/home/user/go/src/github.com/boltdb/bolt/node.go:350 +0xb7
github.com/boltdb/bolt.(*Bucket).spill(0xc420440a98, 0x38a7127b, 0xdcdb00)
	/home/user/go/src/github.com/boltdb/bolt/bucket.go:570 +0x43b
github.com/boltdb/bolt.(*Tx).Commit(0xc420440a80, 0x0, 0x0)
	/home/user/go/src/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/boltdb/bolt.(*DB).Update(0xc4201dc1e0, 0x9b3f50, 0x0, 0x0)
	/home/user/go/src/github.com/boltdb/bolt/db.go:605 +0x10d
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket(0xc4200130c0, 0x0, 0x0)
	/home/user/go/src/github.com/odeke-em/drive/config/config.go:255 +0xaf
github.com/odeke-em/drive/config.(*Context).DeserializeIndex(0xc4200130c0, 0xc4203b4140, 0x1c, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/odeke-em/drive/config/config.go:115 +0x64
github.com/odeke-em/drive/src.(*Commands).deserializeIndex(0xc420013200, 0xc4203b4140, 0x1c, 0xc4201d9978)
	/home/user/go/src/github.com/odeke-em/drive/src/push.go:244 +0x42
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.deserializeIndex)-fm(0xc4203b4140, 0x1c, 0x89a660)
	/home/user/go/src/github.com/odeke-em/drive/src/changes.go:719 +0x3e
github.com/odeke-em/drive/src.resolveConflicts(0xc420032098, 0x1, 0x1, 0x0, 0xc4201d9a90, 0x0, 0xc420032098, 0x1, 0x1, 0x4efbf5, ...)
	/home/user/go/src/github.com/odeke-em/drive/src/changes.go:700 +0x104
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc420013200, 0xc4205800d8, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/odeke-em/drive/src/changes.go:719 +0x1c0
github.com/odeke-em/drive/src.pull(0xc420013200, 0x2, 0x0, 0x0)
	/home/user/go/src/github.com/odeke-em/drive/src/pull.go:117 +0x2e0
github.com/odeke-em/drive/src.(*Commands).Pull(0xc420013200, 0xc42000ae00, 0xc420013200)
	/home/user/go/src/github.com/odeke-em/drive/src/pull.go:71 +0x34
main.(*pullCmd).Run(0xc4200cc2d0, 0xc42000c4d0, 0x0, 0x0, 0xc420176150)
	/home/user/go/src/github.com/odeke-em/drive/cmd/drive/main.go:797 +0x9cd
github.com/odeke-em/command.Run()
	/home/user/go/src/github.com/odeke-em/command/command.go:202 +0x81
github.com/odeke-em/command.ParseAndRun()
	/home/user/go/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/home/user/go/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x1968

$ drive version
drive version: 0.3.9.1
Commit Hash: '8c26f34b24e0e681acfaffee4149edbbd0aec6a2'
Go Version: go1.7.4
OS: linux/amd64
BuildTime: 2017-02-06 12:21:54.104302166 +0100 CET
