### ISSUE TITLE
panic: invalid page type: 27: 10

### ISSUE THREAD

**Issue by sjfloat** [odeke-em/drive#844]
I suddenly can no longer push. 

```
$ drive version
drive version: 0.3.8.1
Commit Hash: '33d8ad314aff64fd2281a39df78d5ef33d050e40'
Go Version: go1.7.4
OS: linux/amd64
BuildTime: 
```
I applied the work-around described in #824 and #839 and re-initialized, but the problem persists.

Here's a typical example. The file is a simple text file.

```

Script started on Sat 14 Jan 2017 08:43:26 AM EST
$ drive diff -skip-content-check NOTES.adoc

 | 
 / 
 – 
 \ 
 | 
 / 
File: /journal/NOTES.adoc
 – 
* local:          2017-01-14T13:26:08.000Z                
* remote:         2017-01-13T09:59:38.000Z                
NOTES.adoc
****

$ drive pull NOTES.adoc

Resolving...
 | 
 / 
 – 
 \ 
 | 
 / 
 – 
 \ 
panic: invalid page type: 27: 10

goroutine 1 [running]:
panic(0x8a3be0, 0xc4204148e0)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*Cursor).search(0xc420475630, 0xc4204148c0, 0x7, 0x8, 0x1b)
	/home/steve/gopath/src/github.com/boltdb/bolt/cursor.go:256 +0x429
github.com/boltdb/bolt.(*Cursor).seek(0xc420475630, 0xc4204148c0, 0x7, 0x8, 0x0, 0x0, 0xc420401400, 0x0, 0x0, 0x0, ...)
	/home/steve/gopath/src/github.com/boltdb/bolt/cursor.go:159 +0xb1
github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc42028c1d8, 0xc4204148c0, 0x7, 0x8, 0xc4204148c7, 0x1, 0x553300)
	/home/steve/gopath/src/github.com/boltdb/bolt/bucket.go:172 +0x124
github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc42028c1d8, 0xc4204148c0, 0x7, 0x8, 0x7, 0x8, 0xc4204148c0)
	/home/steve/gopath/src/github.com/boltdb/bolt/bucket.go:206 +0x4d
github.com/boltdb/bolt.(*Tx).CreateBucketIfNotExists(0xc42028c1c0, 0xc4204148c0, 0x7, 0x8, 0x7, 0x8, 0xc420475798)
	/home/steve/gopath/src/github.com/boltdb/bolt/tx.go:115 +0x4f
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket.func1(0xc42028c1c0, 0x9aeda0, 0xc42028c1c0)
	/home/steve/gopath/src/github.com/odeke-em/drive/config/config.go:247 +0x6f
github.com/boltdb/bolt.(*DB).Update(0xc42017a1e0, 0x9af0e8, 0x0, 0x0)
	/home/steve/gopath/src/github.com/boltdb/bolt/db.go:598 +0xb5
github.com/odeke-em/drive/config.(*Context).CreateIndicesBucket(0xc4201d0640, 0x0, 0x0)
	/home/steve/gopath/src/github.com/odeke-em/drive/config/config.go:255 +0xaf
github.com/odeke-em/drive/config.(*Context).DeserializeIndex(0xc4201d0640, 0xc42040bd60, 0x1c, 0x0, 0x0, 0x0)
	/home/steve/gopath/src/github.com/odeke-em/drive/config/config.go:115 +0x64
github.com/odeke-em/drive/src.(*Commands).deserializeIndex(0xc4201d06c0, 0xc42040bd60, 0x1c, 0xc4204759a0)
	/home/steve/gopath/src/github.com/odeke-em/drive/src/push.go:242 +0x42
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.deserializeIndex)-fm(0xc42040bd60, 0x1c, 0x896de0)
	/home/steve/gopath/src/github.com/odeke-em/drive/src/changes.go:718 +0x3e
github.com/odeke-em/drive/src.resolveConflicts(0xc42002a220, 0x1, 0x1, 0x0, 0xc420475ab8, 0x0, 0xc42002a220, 0x1, 0x1, 0x4eed45, ...)
	/home/steve/gopath/src/github.com/odeke-em/drive/src/changes.go:699 +0x104
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc4201d06c0, 0xc42013c168, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/steve/gopath/src/github.com/odeke-em/drive/src/changes.go:718 +0x1c0
github.com/odeke-em/drive/src.pull(0xc4201d06c0, 0x2, 0x0, 0x0)
	/home/steve/gopath/src/github.com/odeke-em/drive/src/pull.go:116 +0x2bb
github.com/odeke-em/drive/src.(*Commands).Pull(0xc4201d06c0, 0xc42000b300, 0xc4201d06c0)
	/home/steve/gopath/src/github.com/odeke-em/drive/src/pull.go:71 +0x34
main.(*pullCmd).Run(0xc4200d02d0, 0xc42000c2c0, 0x1, 0x1, 0xc4201b7440)
	/home/steve/gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:789 +0x982
github.com/odeke-em/command.Run()
	/home/steve/gopath/src/github.com/odeke-em/command/command.go:202 +0x81
github.com/odeke-em/command.ParseAndRun()
	/home/steve/gopath/src/github.com/odeke-em/command/command.go:209 +0x19
main.main()
	/home/steve/gopath/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x1965
$ exit

exit


```Script done on Sat 14 Jan 2017 08:44:07 AM EST

**Comment by sjfloat** [comment]
Is 33d8ad314aff64fd2281a39df78d5ef33d050e40 meant to be a stable version? Should I prefer another?

**Comment by sjfloat** [comment]
I just completely uninstalled according to:

> Uninstalling
> 
> To remove drive from your computer, you'll need to take out:
> 
> $GOPATH/bin/drive
> $GOPATH/src/github.com/odeke-em/drive
> $GOPATH/pkg/github.com/odeke-em/drive
> $GOPATH/pkg/github.com/odeke-em/drive.a
> Also do not forget to revoke drive's access in case you need to uninstall it.

And I reinstalled:

`go get -u github.com/odeke-em/drive/cmd/drive`

The problem persists.

**Comment by sjfloat** [comment]
Repeated the above, also deleting boltdb. Still no luck.

**Comment by sjfloat** [comment]
This all works fine on a different, similar box. The version of bolt in both places is a705895fdad108f053eae7ee011ed94a0541ee13

**Comment by sjfloat** [comment]
Deleted _drivedb_ and everythings seems good now. The file did not re-appear. What is it's purpose?

`rm ~/gdrive/.gd/drivedb`

**Comment by nelaaro** [comment]
@odeke-em 

I have finished the wiki on how to work aroudn this problem. 
 https://github.com/odeke-em/drive/wiki/Boltdb-breaks-drive-with-(panic:-invalid-page-type:)-or-(panic:--above-high-water-mark)

**Comment by odeke-em** [comment]
@sjfloat boltdb is present to locally keep a copy of remote metadata information about each file so that it can detect conflicts as well as give it more information when a file changes.
My apologies for the really late reply :(, but welcome to drive! Glad to know that deleting boltdb fixed the problem. Yeah there has lately been a bunch of issues popping up with boltdb.

**Comment by odeke-em** [comment]
Hey folks, please get and test out the latest boltdb as per https://github.com/boltdb/bolt/pull/654
You can do so by running
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
and let me know if the problem persists and I'll report back to the boltdb issue.
