### ISSUE TITLE
panic: page 7 already freed

### ISSUE THREAD

**Issue by wsnoble** [odeke-em/drive#862]
I tried pushing a large directory structure with this command:

drive push -quiet 2012-fdr-psm

It yielded the error

panic: page 7 already freed

goroutine 1076622 [running]:
panic(0x8a7240, 0xc4f7e5ba20)
	/net/noble/vol1/home/noble/software/go/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*freelist).free(0xc4f8e98b70, 0xba, 0x7ff145029000)
	/net/noble/vol1/home/noble/work/src/github.com/boltdb/bolt/freelist.go:121 +0x2c0
...

I am running

bash-4.1$ drive version
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime:

My OS is CentOS Release 6.8 with linux kernel 2.6.32.

Full output log is attached.
[drive.txt](https://github.com/odeke-em/drive/files/730798/drive.txt)

**Comment by odeke-em** [comment]
Hello again @wsnoble, thank you for reporting this issue. 

This does look similar to the boltdb issues that have been popping up.
Might your Go version by any chance be < go1.7?

**Comment by wsnoble** [comment]
No, I am using go 1.7.4:

-bash-4.1$ go version

go version go1.7.4 linux/amd64


I will try the stuff on the wiki entry you sent.

Bill



On Thu, Jan 26, 2017 at 11:42 PM, Emmanuel T Odeke <notifications@github.com

**Comment by erdoking** [comment]
same here.
This problem seem to start after "drive delete" operations ...
i used it into lxc-container (Proxmox) - Debian jessie (all updates).

drive push start working again after container restart and stop working after some delete operations ...

```
drive version
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 
```

```
# aptitude show drive
Paket: drive                                    
Neu: ja
Zustand: Installiert
Automatisch installiert: nein
Version: 0.3.9.1-1
Priorität: extra
Bereich: net
Verwalter: John Jenkins <twodopeshaggy@gmail.com>
Architektur: amd64
Unkomprimierte Größe: 15,3 M
Beschreibung: Google Drive tool written in Go language
 Command line tool for managing data on Google drive.
```

**/usr/lib/go-1.7/src/runtime/panic.go:500** 
This directory doesn't exist!!


```
# drive push
...
Addition count 35 src: 60.06GB
Proceed with the changes? [Y/n]:y
 41943552 / 64490062991 [>------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.07% 1h7m40spanic: page 8 already freed

goroutine 45 [running]:
panic(0x55f028335da0, 0xc4204907b0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/boltdb/bolt.(*freelist).free(0xc420374c90, 0xdd3, 0x7f8a8f413000)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/freelist.go:121 +0x2c0
github.com/boltdb/bolt.(*node).spill(0xc420056a80, 0xc42045ba80, 0xc42045ba80)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/node.go:363 +0x1dc
github.com/boltdb/bolt.(*node).spill(0xc420056a10, 0xc420374db0, 0xc4201f7720)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/node.go:350 +0xb7
github.com/boltdb/bolt.(*Bucket).spill(0xc4201bccc0, 0xc420374c00, 0xc4201f7990)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/bucket.go:570 +0x43b
github.com/boltdb/bolt.(*Bucket).spill(0xc4202fe018, 0x55f034c20c36, 0x55f02885c540)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/bucket.go:537 +0x93b
github.com/boltdb/bolt.(*Tx).Commit(0xc4202fe000, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/boltdb/bolt.(*DB).Update(0xc420498000, 0xc4201f7bf8, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/boltdb/bolt/db.go:605 +0x10d
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc420054ec0, 0xc42006ef00, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/config/config.go:279 +0x1a8
github.com/odeke-em/drive/src.(*Commands).remoteMod(0xc420055040, 0xc420367380, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/push.go:404 +0x4b3
github.com/odeke-em/drive/src.(*Commands).remoteAdd(0xc420055040, 0xc420367380, 0x0, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/push.go:414 +0x35
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.remoteAdd)-fm(0xc420367380, 0x1, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:1085 +0x34
github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0xc4204e6ec0, 0x55f027ea8f85, 0x55f028331220, 0xc420566f00)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:120 +0xb1
github.com/odeke-em/drive/src.jobSt.Do(0x6, 0xc4203d9520, 0x55f02809011f, 0x55f028331220, 0xc420566f00, 0x0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:100 +0x27
github.com/odeke-em/drive/src.(*jobSt).Do(0xc4203d67e0, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:6 +0x5b
github.com/odeke-em/semalim.Run.func4.1(0xc4203c74b0, 0xc420566e40, 0xc4203c74c0, 0xc4203c74d0, 0x55f028843780, 0xc4203d67e0)
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/semalim/semalim.go:71 +0x56
created by github.com/odeke-em/semalim.Run.func4
        /build/drive-tyASL_/drive-0.3.9.1/src/github.com/odeke-em/semalim/semalim.go:76 +0x141
```

**Comment by ptman** [comment]
same problem as well

drive version: 0.3.9.1
Commit Hash: 'a3f2f281cc3536bfc116a34eb8e00bdd75b416e7'
Go Version: go1.7.4
OS: linux/amd64
BuildTime: 2017-01-31 10:31:06.171148765 +0200 EET

**Comment by odeke-em** [comment]
Thanks y'all for the patience. I think it's high time that we ping the boltdb folks.

**Comment by odeke-em** [comment]
Hey folks, please get and test out the latest boltdb as per https://github.com/boltdb/bolt/pull/654
You can do so by running
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```
and let me know if the problem persists and I'll report back to the boltdb issue.

**Comment by ptman** [comment]
Still suffering the same problem

**Comment by odeke-em** [comment]
@ptman what is the git commit that you have in $GOPATH/src/github.com/boltdb/bolt?

**Comment by ptman** [comment]
git describe --always
    e9cf4fa

**Comment by odeke-em** [comment]
Thank you @ptman for the confirmation, I've tagged you in the boltdb discussion.

**Comment by ptman** [comment]
I have a somewhat large number of files. Or at least I don't usually wait around for drive to figure out which files it wants to sync.

**Comment by odeke-em** [comment]
Can you isolate a single test directory e.g
```shell
$ mkdir -p test-drive-862
$ for ((i=0; i < 10; i++)) do date > test-drive-862/$i.txt;done
$ drive push --depth -1 test-drive-862
```
and then we can use that for testing

**Comment by odeke-em** [comment]
And to repeat the tests, you can run delete on `test-drive-862` e.g
```shell
$ # Test Run #3
$ drive delete test-drive-862
```
and then we can repeat the tests

**Comment by ptman** [comment]
exporting seems to trigger it more reliably

**Comment by mkruisselbrink** [comment]
Getting many of these and similar ("panic: assertion failed: write: circular dependency occurred") errors myself too when trying to push even small folders...

**Comment by blaskovic** [comment]
I have exactly the same issue.. Can I somehow help you with fixing that? I can provide any information, just let me know, what you need.

**Comment by bixiou** [comment]
Still no fix on this issue?
