### ISSUE TITLE
Pull failing with panic: page 4 already freed

### ISSUE THREAD

**Issue by Massimo-B** [odeke-em/drive#934]
Hi, I tried drive-0.3.9 on Gentoo.

However when trying to do a huge global drive pull I got lots of name clashes like this:
```
...
X /TitaniumBackup/MotoMo/com.android.egg-e125ea391ffc6516ef0200ad9061c10e.apk.bz2 0B4vIxE1EMTq6U1NIMWZ5a0F3NWs
X /TitaniumBackup/MotoMo/com.android.egg-e125ea391ffc6516ef0200ad9061c10e.apk.bz2 0B4vIxE1EMTq6WWtFeVRONjZCbHc

clashes detected. Use `ignore-name-clashes` to override this behavior or `fix-clashes` to try fixing this
```
Then I tried drive pull -ignore-name-clashes. I did not like to try -fix-clashes as this would rename stuff and break the naming convention of TitaniumBackup probably:
```
...
+ /TitaniumBackup/TF700T/com.google.android.apps.chromecast.app-7ca28f78e3baca576d53c64efccb2ffc.apk.bz2
+ /TitaniumBackup/TF700T/de.finanzen100-3c15b94f8364b8462ce901b323cc1b0f.apk.bz2
Addition count 1498 src: 2.43GB
Proceed with the changes? [Y/n]:Y
 8203399 / 2611955088 [>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.31% 40m13spanic: page 4 already freed

goroutine 323 [running]:
github.com/boltdb/bolt.(*freelist).free(0xc42099bf20, 0x43, 0x7f95d029d000)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/freelist.go:121 +0x29a
github.com/boltdb/bolt.(*node).spill(0xc420a27ab0, 0xc420326080, 0xe0c620)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/node.go:363 +0x1e0
github.com/boltdb/bolt.(*node).spill(0xc420a279d0, 0xc420d48030, 0xc42004c710)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/node.go:350 +0xb4
github.com/boltdb/bolt.(*Bucket).spill(0xc42078b540, 0xc42099bf00, 0xc42004c980)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/bucket.go:570 +0x17b
github.com/boltdb/bolt.(*Bucket).spill(0xc420206398, 0x22a9eacd, 0xe33980)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/bucket.go:537 +0x8f8
github.com/boltdb/bolt.(*Tx).Commit(0xc420206380, 0x0, 0x0)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/tx.go:163 +0x125
github.com/boltdb/bolt.(*DB).Update(0xc420134960, 0xc42004cbe8, 0x0, 0x0)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/db.go:605 +0xf7
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc42009aec0, 0xc4207be780, 0x0, 0x0)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/config/config.go:279 +0x164
github.com/odeke-em/drive/src.(*Commands).createIndex(0xc42009af80, 0xc420027e40, 0x0, 0xc42004ccc0)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/fetch.go:314 +0x113
github.com/odeke-em/drive/src.(*Commands).localAdd.func1(0xc42004cd88, 0xc4203be980, 0xc42009af80)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/pull.go:574 +0x63
github.com/odeke-em/drive/src.(*Commands).localAdd(0xc42009af80, 0xc4203be980, 0x0, 0x0, 0x0, 0x0, 0x0)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/pull.go:605 +0x22e
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.localAdd)-fm(0xc4203be980, 0x0, 0x0, 0x0, 0xc420af4e08, 0x42c65e)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/misc.go:1066 +0x52
github.com/odeke-em/drive/src.(*Commands).playPullChanges.func2.1(0xc4203be980, 0xc, 0xc4200326e0)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/pull.go:477 +0x4d
github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0xc420af4ee0, 0x406685, 0x8dc3e0, 0xc4209fc960)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/misc.go:120 +0xaf
github.com/odeke-em/drive/src.jobSt.Do(0x4d, 0xc420327920, 0x754acf, 0x8dc3e0, 0xc4209fc960, 0x0)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/misc.go:100 +0x27
github.com/odeke-em/drive/src.(*jobSt).Do(0xc42030f4c0, 0x0, 0x0, 0x0, 0x0)
   <autogenerated>:6 +0x56
github.com/odeke-em/semalim.Run.func4.1(0xc42030e280, 0xc4209fc660, 0xc42030e290, 0xc42030e2d0, 0xe0b160, 0xc42030f4c0)
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/semalim/semalim.go:71 +0x56
created by github.com/odeke-em/semalim.Run.func4
   /var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/semalim/semalim.go:76 +0x141
```

**Comment by Massimo-B** [comment]
Any news on that?
I have the same issue on completely different GDrive accounts. Some files are pulled but not all, and the error is:
```
$ drive pull -ignore-name-clashes
Resolving...
panic: invalid page type: 20: 10

goroutine 1 [running]:
github.com/boltdb/bolt.(*Cursor).search(0xc4201b7618, 0xc4201b7688, 0x1c, 0x20, 0x14)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/cursor.go:256 +0x405
github.com/boltdb/bolt.(*Cursor).searchPage(0xc4201b7618, 0xc4201b7688, 0x1c, 0x20, 0x7f3113022000)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/cursor.go:314 +0x156
github.com/boltdb/bolt.(*Cursor).search(0xc4201b7618, 0xc4201b7688, 0x1c, 0x20, 0x18)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/cursor.go:271 +0x1bb
github.com/boltdb/bolt.(*Cursor).seek(0xc4201b7618, 0xc4201b7688, 0x1c, 0x20, 0x0, 0x0, 0xc42018a178, 0xc4202848d8, 0xc4202f7720, 0x1, ...)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/cursor.go:159 +0xb1
github.com/boltdb/bolt.(*Bucket).Get(0xc420537300, 0xc4201b7688, 0x1c, 0x20, 0x1c, 0x20, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/bucket.go:267 +0xef
github.com/odeke-em/drive/config.(*Context).DeserializeIndex.func1(0xc4202848c0, 0x9d1d50, 0xc4202848c0)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/config/config.go:134 +0x10c
github.com/boltdb/bolt.(*DB).View(0xc4201005a0, 0xc4201b77a0, 0x0, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/boltdb/bolt/db.go:629 +0x9f
github.com/odeke-em/drive/config.(*Context).DeserializeIndex(0xc42001d0c0, 0xc42028c960, 0x1c, 0x0, 0x0, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/config/config.go:140 +0x13f
github.com/odeke-em/drive/src.(*Commands).deserializeIndex(0xc42001d180, 0xc42028c960, 0x1c, 0x20)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/push.go:242 +0x42
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.deserializeIndex)-fm(0xc42028c960, 0x1c, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/changes.go:719 +0x3e
github.com/odeke-em/drive/src.resolveConflicts(0xc42030e480, 0x3, 0x4, 0xc420560400, 0xc4201b7a20, 0x8, 0xc42030e480, 0x3, 0x4, 0xa, ...)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/changes.go:700 +0x104
github.com/odeke-em/drive/src.(*Commands).resolveConflicts(0xc42001d180, 0xc4203da140, 0xa, 0xa, 0x0, 0x0, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/changes.go:719 +0x1cc
github.com/odeke-em/drive/src.pull(0xc42001d180, 0x2, 0x1, 0xc42000ae00)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/pull.go:116 +0x294
github.com/odeke-em/drive/src.(*Commands).Pull(0xc42001d180, 0xc42000ae00, 0xc42001d180)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/src/pull.go:71 +0x34
main.(*pullCmd).Run(0xc420154000, 0xc4200106b0, 0x0, 0x0, 0xc42014e390)
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/cmd/drive/main.go:789 +0x98c
github.com/odeke-em/command.Run()
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/command/command.go:202 +0x7a
github.com/odeke-em/command.ParseAndRun()
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/command/command.go:209 +0x25
main.main()
	/var/tmp/portage/net-misc/drive-0.3.9/work/drive-0.3.9/src/github.com/odeke-em/drive/cmd/drive/main.go:126 +0x1737
```

**Comment by Massimo-B** [comment]
Today this is net-misc/drive-0.3.9.1 and still failing with the same issue just other files:

```
Modification count 4
Deletion count 10
Addition count 1131 src: 2.63GB
Proceed with the changes? [Y/n]:Y
 0 / 2822791797 [-----------------------------------------------------------------------------------------------------------------]   0.00%panic: page 4 already freed

goroutine 284 [running]:
github.com/odeke-em/drive/vendor/github.com/boltdb/bolt.(*freelist).free(0xc4206941e0, 0x51, 0x7f19f8007000)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/boltdb/bolt/freelist.go:121 +0x2eb
github.com/odeke-em/drive/vendor/github.com/boltdb/bolt.(*node).spill(0xc4201c2150, 0xc4203a81c0, 0xa232c0)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/boltdb/bolt/node.go:363 +0x1fa
github.com/odeke-em/drive/vendor/github.com/boltdb/bolt.(*node).spill(0xc4201c20e0, 0xc4206942d0, 0xc4209cf708)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/boltdb/bolt/node.go:350 +0xbf
github.com/odeke-em/drive/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc420550a00, 0xc420694200, 0xc4209cf980)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/boltdb/bolt/bucket.go:570 +0x4b8
github.com/odeke-em/drive/vendor/github.com/boltdb/bolt.(*Bucket).spill(0xc4204220f8, 0x75d427a67, 0xec7c80)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/boltdb/bolt/bucket.go:537 +0x3f9
github.com/odeke-em/drive/vendor/github.com/boltdb/bolt.(*Tx).Commit(0xc4204220e0, 0x0, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/boltdb/bolt/tx.go:163 +0x11f
github.com/odeke-em/drive/vendor/github.com/boltdb/bolt.(*DB).Update(0xc42020c1e0, 0xc4209cfbd8, 0x0, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/boltdb/bolt/db.go:605 +0xe8
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc4200c6b80, 0xc4208f6180, 0x0, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/config/config.go:270 +0x140
github.com/odeke-em/drive/src.(*Commands).createIndex(0xc4200c6c40, 0xc420598b00, 0xc420064cc0, 0x42a994)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/src/fetch.go:314 +0x156
github.com/odeke-em/drive/src.(*Commands).localMod.func1(0xc420064d88, 0xc42059c6c0, 0xc4200c6c40)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:529 +0x5c
github.com/odeke-em/drive/src.(*Commands).localMod(0xc4200c6c40, 0xc42059c6c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:567 +0x28e
github.com/odeke-em/drive/src.(*Commands).(github.com/odeke-em/drive/src.localMod)-fm(0xc42059c6c0, 0x0, 0x0, 0x0, 0x42d24a, 0x9df840)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:1062 +0x52
github.com/odeke-em/drive/src.(*Commands).playPullChanges.func2.1(0xc42059c6c0, 0x9df848, 0xc42063ac00)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/src/pull.go:478 +0x4d
github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0x63222020200a2c7d, 0x74696c6962617061, 0xc4205d1ee8, 0x405fdb)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:120 +0xab
github.com/odeke-em/drive/src.jobSt.Do(0xb, 0xc4203fc200, 0xc4205d1f08, 0x74e543, 0xc420777bc0, 0x0)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/src/misc.go:100 +0x27
github.com/odeke-em/drive/vendor/github.com/odeke-em/semalim.Run.func4.1(0xc420467c60, 0xc420777aa0, 0xc420467c70, 0xc420467c80, 0xa21c40, 0xc420467d60)
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/odeke-em/semalim/semalim.go:71 +0x56
created by github.com/odeke-em/drive/vendor/github.com/odeke-em/semalim.Run.func4
	/var/tmp/portage/net-misc/drive-0.3.9.1/work/drive-0.3.9.1/src/github.com/odeke-em/drive/vendor/github.com/odeke-em/semalim/semalim.go:68 +0x113
```

**Comment by Massimo-B** [comment]
Is there any solution for this issue?

**Comment by Massimo-B** [comment]
Hi, this tool looks powerful and promising but never worked for me. Is there any progress here? What is wrong with my simple pull?

**Comment by odeke-em** [comment]
Could you use the binaries on the release page perhaps? Seems like faults
are happening on your system for a failure in the boltdb library which we
don’t maintain. Let’s start with those.

**Comment by Massimo-B** [comment]
Ok, I took the binary from https://github.com/odeke-em/drive/releases/download/v0.4.0/drive_linux
However drive version still says
```
drive version: 0.3.9.1
```

The error looks the same. Doing ```drive pull```, I get some paths clash, doing ```drive pull -ignore-name-clashes``` the pull starts but ends with
```
...
Addition count 179 src: 9.15MB
Proceed with the changes? [Y/n]: Y
 0 / 9593498 [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%panic: page 4 already freed

goroutine 225 [running]:
github.com/boltdb/bolt.(*freelist).free(0xc0002ac420, 0x6d, 0x7f599602b000)
	/Users/emmanuelodeke/go/src/github.com/boltdb/bolt/freelist.go:121 +0x2aa
github.com/boltdb/bolt.(*node).spill(0xc000292150, 0xc000456120, 0x1)
	/Users/emmanuelodeke/go/src/github.com/boltdb/bolt/node.go:363 +0x405
github.com/boltdb/bolt.(*node).spill(0xc0002920e0, 0xc0002ac600, 0xc0003a17b8)
	/Users/emmanuelodeke/go/src/github.com/boltdb/bolt/node.go:350 +0xba
github.com/boltdb/bolt.(*Bucket).spill(0xc0000fc240, 0xc0002ac400, 0xc0003a19a8)
	/Users/emmanuelodeke/go/src/github.com/boltdb/bolt/bucket.go:570 +0x49a
github.com/boltdb/bolt.(*Bucket).spill(0xc0005d6018, 0x75fafd7ad, 0xf02040)
	/Users/emmanuelodeke/go/src/github.com/boltdb/bolt/bucket.go:537 +0x3f6
github.com/boltdb/bolt.(*Tx).Commit(0xc0005d6000, 0x0, 0x0)
	/Users/emmanuelodeke/go/src/github.com/boltdb/bolt/tx.go:163 +0xe8
github.com/boltdb/bolt.(*DB).Update(0xc00000a1e0, 0xc0003a1bf8, 0x0, 0x0)
	/Users/emmanuelodeke/go/src/github.com/boltdb/bolt/db.go:605 +0x105
github.com/odeke-em/drive/config.(*Context).SerializeIndex(0xc0002b9400, 0xc0001361e0, 0x0, 0x0)
	/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/config/config.go:274 +0x15f
github.com/odeke-em/drive/src.(*Commands).createIndex(0xc00013b980, 0xc000702c00, 0x2, 0x2)
	/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/src/fetch.go:314 +0x125
github.com/odeke-em/drive/src.(*Commands).localAdd.func1(0xc0006a8de8, 0xc00003c600, 0xc00013b980)
	/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/src/pull.go:575 +0x65
github.com/odeke-em/drive/src.(*Commands).localAdd(0xc00013b980, 0xc00003c600, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/src/pull.go:606 +0x2fe
github.com/odeke-em/drive/src.(*Commands).playPullChanges.func2.1(0xc00003c600, 0x0, 0x0)
	/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/src/pull.go:478 +0x4d
github.com/odeke-em/drive/src.(*changeJobSt).changeJober.func1(0xc000673f08, 0x927213, 0xc000204300, 0x0)
	/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/src/misc.go:119 +0xa7
github.com/odeke-em/drive/src.jobSt.Do(...)
	/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/src/misc.go:99
github.com/odeke-em/semalim.Run.func4.1(0xc00032d7d0, 0xc000204240, 0xc00032d7e0, 0xc00032d7f0, 0xba6c68, 0xc0005b4020)
	/Users/emmanuelodeke/go/src/github.com/odeke-em/semalim/semalim.go:71 +0x56
created by github.com/odeke-em/semalim.Run.func4
	/Users/emmanuelodeke/go/src/github.com/odeke-em/semalim/semalim.go:68 +0x118
```
